# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
#   namespace: studyduo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#       - name: backend
#         image: europe-west1-docker.pkg.dev/stackup-gemini/studyduo/backend:2.0
#         ports:
#         - containerPort: 5000
#         envFrom:
#         - secretRef:
#             name: app-secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: studyduo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: europe-west1-docker.pkg.dev/stackup-gemini/studyduo/backend:2.0
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: google-cloud-key
          mountPath: "/var/secrets/google"
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/var/secrets/google/key.json"
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcp-sa-key