apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: studyduo
spec:
  type: NodePort
  ports:
    - port: 80      
      targetPort: 3000  
  selector:
    app: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: studyduo
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000  
  selector:
    app: backend
